sudo: required
language: python
services:
  - docker
before_install: 
  - docker pull cuonglekty/alpine-python-protobuf
script:
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
