sudo: required
language: python
services:
  - docker
before_install: 
  - docker pull cuonglekty/alpine-python-protobuf
  - docker images
  - pwd
  - ls -laR
  - docker run cuonglekty/alpine-python-protobuf / "pwd; ls -laR"
script:
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
