sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - python
      - python-pip
script:
  - pwd
  - pip install protobuf3
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
