sudo: required
language: python
install:
  - wget https://protobuf.googlecode.com/files/protobuf-2.4.1.tar.gz
  - tar -xzvf protobuf-2.4.1.tar.gz
  - pushd protobuf-2.4.1 && ./configure --prefix=/usr && make && sudo make install && popd
script:
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
