sudo: required
language: python
services:
  - docker
script:
  - docker pull cuonglekty/alpine-python-protobuf
  - docker run cuonglekty/alpine-python-protobuf
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
