sudo: true
cache:
  directories:
  - $HOME/protobuf
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - python
install:
  - ls -la
  - bash install_protobuf.sh
  - pwd
before_script:
  - pwd
  - ls -Rla $HOME/protobuf
  - cp -R $HOME/build/Shivam010/Protocol-Buffer-to-TypeScript-Plugin/* $HOME/protobuf
  - ls -la
  - cd $HOME/protobuf
  - pwd
script:
  - pwd
  - ls -la
  - chmod -R 777 .
  - cd examples
  - bash ./generate.sh
  - ls -la
