sudo: true
cache:
  directories:
  - $HOME/protobuf
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - python
install:
  - ls -la
  - bash install_protobuf.sh
before_script:
  - pwd
  - ls -Rla $HOME/protobuf
script:
  - pwd
  - ls -la
  - chmod -R 777 .
  - cd examples
  - bash ./generate.sh
  - ls -la
