sudo: true
cache:
  directories:
  - $HOME/protobuf
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - python
install:
  - ls -la
  - bash install_protobuf.sh
  - pwd
  - ls -la
before_script:
  - ls -Rla $HOME/protobuf
  - cp -R $HOME/build/Shivam010/Protocol-Buffer-to-TypeScript-Plugin/* $HOME/protobuf/bin/
  - cp -R $HOME/protobuf/bin/protobuf-3.6.1/python/google $HOME/protobuf/bin/
  - ls -la
  - cd $HOME/protobuf/bin
script:
  - cd examples
  - bash ./generate.sh
  - ls -la
