sudo: required
language: python
services:
  - docker
before_install: 
  - docker pull cuonglekty/alpine-python-protobuf
  - docker images
  - pwd
  - ls -laR
  - docker run cuonglekty/alpine-python-protobuf /bin/sh "cd /home/travis/build/Shivam010/Protocol-Buffer-to-TypeScript-Plugin/examples; bash ./generate.sh"
  - pwd
  - ls -la
script:
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd examples
  - bash ./generate.sh
  
