sudo: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - python
install:
  - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-python-3.6.1.tar.gz
  - ls -l
  - tar -xzvf protobuf-python-3.6.1.tar.gz
  - pushd protobuf-3.6.1 && ./configure --prefix=/usr && make && sudo make install && popd
script:
  - pwd
  - chmod -R 777 .
  - ls -la
  - cd protobuf-3.6.1/python
  - python setup.py build
  - python setup.py test
  - cp ../../examples ./examples
  - cp ../../tsPlugin.py ./tsPlugin.py
  - cd examples
  - bash ./generate.sh
  
